---
- name: Fail if unsupported CentOS version
  fail:
    msg: "CentOS 7 or later is required!"
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version < '7'

- name: Fail if unsupported Fedora version
  fail:
    msg: "Fedora 24 or later is required!"
  when: ansible_distribution == "Fedora" and
        ansible_distribution_major_version < '24'

- name: Fail if unsupported Ubuntu version
  fail:
    msg: "Ubuntu 14 or later is required!"
  when: ansible_distribution == "Ubuntu" and
        ansible_distribution_major_version < '14'

- name: Fail if unsupported Debian version
  fail:
    msg: "Debian 8 (jessie) or later is required!"
  when: ansible_distribution == "Debian" and
        ansible_distribution_major_version < '8'

- name: Fail if this roles does not support the distribution
  fail:
    msg: "Distribution {{ ansible_distribution }} is not supported by this role!"
  when: ansible_distribution != "Fedora" and
        ansible_distribution != "CentOS" and
        ansible_distribution != "Ubuntu" and
        ansible_distribution != "Debian"
