---
- include: distribution-check.yml

- include: setup-repository.yml

- include: kernel-3-mount-fixes.yml
  when: ansible_kernel | version_compare('4', '<')

- include: setup-audit.yml

- include: remove-pre-docker-ce.yml
  when: docker_remove_pre_ce | bool

- include: install-docker.yml

- include: configure-docker.yml
