---
# tasks file for ansible-role-docker-ce

- name: Add Docker CE repository
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: true
  register: dnf_repo

- name: Update dnf cache
  shell: dnf makecache fast
  become: true
  when: dnf_repo.changed

- name: Install python and deps for ansible modules
  raw: dnf install -y python2 python2-dnf libselinux-python
  become: true
  changed_when: false

- include: main-Storage.yml
  when: docker_setup_devicemapper == true

- include: main-Generic.yml