---
# tasks file for ansible-role-docker-ce

- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  become: true
  register: dnf_repo

- name: Determine Docker CE Edge repo status
  shell: dnf config-manager --dump docker-ce-edge | grep enabled
  ignore_errors: yes
  changed_when: false
  register: cmd_docker_ce_edge_enabled

- name: Set current Docker CE Edge repo status fact
  set_fact:
    fact_docker_ce_edge_enabled: "{{ cmd_docker_ce_edge_enabled.stdout == 'enabled = True' }}"

- name: Enable/Disable Docker CE Edge Repository
  shell: dnf config-manager --set-{{ (docker_enable_ce_edge == true) | ternary('enabled','disabled') }} docker-ce-edge
  become: true
  when: fact_docker_ce_edge_enabled != docker_enable_ce_edge

- name: Update dnf cache
  shell: dnf makecache fast
  become: true
  when: dnf_repo.changed

- name: Install python and deps for ansible modules
  raw: dnf install -y python2 python2-dnf libselinux-python
  become: true
  changed_when: false

- include: main-Storage.yml
  when: docker_setup_devicemapper == true

- include: main-Generic.yml